# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*[Tt]est*/*.csproj'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
- task: PublishPipelineArtifact@1
  displayName: Collect Code Coverage
  inputs:
    targetPath: $(build.artifactStagingDirectory)
    artifact: 'drop'
    publishLocation: 'pipeline'
- task: AzureWebApp@1
  displayName: Deploy
  inputs:
    azureSubscription: 'AJS-DevOps-Svc-Connection'
    appType: 'webAppLinux'
    appName: 'ajsSampleAPI'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
